syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.examples.contam";
option java_outer_classname = "ContamWorldProto";
option objc_class_prefix = "HLW";

package contam;

// The Contam service definition.
service ContamServer {
  // Sends a greeting
  rpc RunContam (ContamRequest) returns (ContamReply) {}

  rpc RunContamStreamReply (ContamRequest) returns (stream ContamReply) {}

  rpc RunContamBidiStream (stream ContamRequest) returns (stream ContamReply) {}
}

// The request message containing the Contam project.
message ContamRequest {
  bytes prj = 1;
  bool ach = 2;
  bool cex = 3;
  bool csm = 4;
  bool log = 5;
  bool rst = 6;
  bool sim = 7;
  bool xlog = 8;
}

// The response message from contam simulation service
message ContamReply {
  bytes stdout = 1;
  bytes stderr = 2;
  bytes ach = 3;
  bytes cex = 4;
  bytes csm = 5;
  bytes log = 6;
  bytes rst = 7;
  bytes sim = 8;
  bytes xlog = 9;
}
